package eryingzhang.net.mapper;

import eryingzhang.net.pojo.ProfessionalCompetition;

public interface ProfessionalCompetitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalcompetition_
     *
     * @mbg.generated Thu Oct 29 15:30:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalcompetition_
     *
     * @mbg.generated Thu Oct 29 15:30:59 CST 2020
     */
    int insert(ProfessionalCompetition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalcompetition_
     *
     * @mbg.generated Thu Oct 29 15:30:59 CST 2020
     */
    int insertSelective(ProfessionalCompetition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalcompetition_
     *
     * @mbg.generated Thu Oct 29 15:30:59 CST 2020
     */
    ProfessionalCompetition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalcompetition_
     *
     * @mbg.generated Thu Oct 29 15:30:59 CST 2020
     */
    int updateByPrimaryKeySelective(ProfessionalCompetition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalcompetition_
     *
     * @mbg.generated Thu Oct 29 15:30:59 CST 2020
     */
    int updateByPrimaryKey(ProfessionalCompetition record);
}